include: "rules/createivf.smk"

rule all_basecall:
    input: get_basecall_output

rule all_map:
    input:
        expand("{analysis_root}/{sample}/mapped-pipeline/{run_name}.minimap.sorted.bam.bai", analysis_root=config['analysis_root'], run_name=config['run_name'], sample=config['sample'])

rule all_merge:
    input:
        expand("{analysis_root}/{sample}/merged.sorted.bam.bai", analysis_root=config['analysis_root'], sample=config['sample'])

rule all_bp:
    input:
        get_breakpoint_reads

rule all_stats:
    input:
        expand("{analysis_root}/{sample}/basecalling/{run_name}_read_stats.tsv", analysis_root=config['analysis_root'], sample=config['sample'], run_name=config['run_name'])

