---
name: createivf
channels:
    - anaconda
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python=3.9
    - snakemake
    - minimap2
    - pysam
    - samtools
    - zlib
    - pip:
        - NanoPlot
        - pybedtools

